### ISSUE TITLE
uploadStream functionality not implemented

### ISSUE THREAD

**Issue by StevenLangbroek** [paulospiguel/strapi-provider-upload-supabase-v4#3]
Hey! I've been trying this plugin out, and am running into an issue:

When my Strapi instance starts, I see this error:

```bash
(node:30967) Warning: The upload provider "strapi-provider-upload-supabase-v4" doesn't implement the uploadStream function. Strapi will fallback on the upload method. Some performance issues may occur.
```

I didn't think much of it, as uploading worked normally when creating or editing content. When I tried to change the auth & sidebar logo though (Settings -> Overview), I got a 500 error from my server. I found this in the logs, so it would seem this functionality is _needed_ somehow:

```bash
Feb 1 02:16:15 PM  TypeError: strapi.plugin(...).provider.uploadStream is not a function
Feb 1 02:16:15 PM      at /opt/render/project/src/node_modules/@strapi/admin/server/services/project-settings.js:88:55
Feb 1 02:16:15 PM      at Array.map (<anonymous>)
Feb 1 02:16:15 PM      at uploadFiles (/opt/render/project/src/node_modules/@strapi/admin/server/services/project-settings.js:88:8)
Feb 1 02:16:15 PM      at Object.updateProjectSettings (/opt/render/project/src/node_modules/@strapi/admin/server/services/project-settings.js:130:9)
Feb 1 02:16:15 PM      at runMicrotasks (<anonymous>)
Feb 1 02:16:15 PM      at processTicksAndRejections (node:internal/process/task_queues:96:5)
Feb 1 02:16:15 PM      at async returnBodyMiddleware (/opt/render/project/src/node_modules/@strapi/strapi/lib/services/server/compose-endpoint.js:52:18)
Feb 1 02:16:15 PM      at async policiesMiddleware (/opt/render/project/src/node_modules/@strapi/strapi/lib/services/server/policy.js:24:5)
Feb 1 02:16:15 PM      at async /opt/render/project/src/node_modules/@strapi/strapi/lib/middlewares/body.js:58:9
Feb 1 02:16:15 PM      at async /opt/render/project/src/node_modules/@strapi/strapi/lib/middlewares/logger.js:25:5
```

Is this expected? I was a little surprised, given the wording on the startup warning. If this is simply not implemented yet, if you can give me a few pointers where to look or a reference implementation, I can implement the required changes for you.

**Comment by rustkas** [comment]
I fix that issue just using other plugin implementation [strapi-provider-upload-supabase-strage](https://www.npmjs.com/package/strapi-provider-upload-supabase-strage?activeTab=readme)

**Comment by StevenLangbroek** [comment]
@rustkas thanks, I'd still love to get the fix upstream instead of what's happening now (forks of forks of forks). @paulospiguel how can i help?

**Comment by paulospiguel** [comment]
@StevenLangbroek Which node version do you use? This plugin uses up to node version 16.x.x.

**Comment by StevenLangbroek** [comment]
@paulospiguel I'm running 16.17.1, on render.com.
